version: "3.0"

services:
  
  redis:
    image: "redis"
    ports: 
      - "6379:6379"

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - ./:/app/
    tty: true
    depends_on:
      - "redis"
    environment:
      REDIS_DSN: "redis://redis:6379/0"
    ports:
      - "80:80"
