pipelines:
  pipeline2:
    group: first
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    environment_variables:
      EKS_CLUSTER: some-value
    materials:
      git:
        shallow_clone: false
        auto_update: true
        git: https://github.com/melhin/streamchat
        branch: gocd_slacker
    stages:
    - stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          job:
            timeout: 0
            tasks:
            - exec:
                command: ls