name: Check Test
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Where do you want to deploy'     
        required: true
      tags:
        description: 'Test scenario tags'  
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}" 
