name: Check Test
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Where do you want to deploy'     
        required: true
      tags:
        description: 'Test scenario tags'  
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - env:
        NAMESPACE: "${{ github.event.inputs.logLevel }}"
        DOMAIN: "${{ github.event.inputs.logLevel }}.nihlem.it"
      run: |
        echo "NameSpace: $NAMESPACE"
        echo "DOMAIN: $DOMAIN" 
